"""initial db setup with dims, subdims and indicators

Revision ID: 31bb57c4f937
Revises: 
Create Date: 2020-01-27 13:19:15.565647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bb57c4f937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dimension_timestamp'), 'dimension', ['timestamp'], unique=False)
    op.create_table('subdimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subdimension_timestamp'), 'subdimension', ['timestamp'], unique=False)
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('criteria', sa.String(length=128), nullable=True),
    sa.Column('subdimension_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subdimension_id'], ['subdimension.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria')
    )
    op.create_index(op.f('ix_indicator_timestamp'), 'indicator', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicator_timestamp'), table_name='indicator')
    op.drop_table('indicator')
    op.drop_index(op.f('ix_subdimension_timestamp'), table_name='subdimension')
    op.drop_table('subdimension')
    op.drop_index(op.f('ix_dimension_timestamp'), table_name='dimension')
    op.drop_table('dimension')
    # ### end Alembic commands ###
